In [105]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [106]:
data=pd.read_csv("C:\\Users\\supriya\\Downloads\\data cleaning\\data cleaning\\Churn_Modelling.csv")


In [107]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [108]:
#drop irrelevant columns
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)


In [109]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [110]:
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[["Geography"]])

In [111]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [112]:
#encode categorical columns
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])

In [113]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [114]:
onehot_encoder_geo.get_feature_names_out(["Geography"])


array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [115]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [116]:
df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))

In [117]:
#combine One Hot Encoder columns with orginal data
data=pd.concat([data.drop("Geography",axis=1),df],axis=1)



In [118]:
df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [119]:
#save the encoders and scaler
with open("LabelEncoder_gender.pkl","wb") as file:
    pickle.dump(label_encoder_gender,file)
with open("OneHotEncoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)
    

In [120]:
#divide data into input and output features
X=data.drop("Exited",axis=1)
y=data["Exited"]

In [121]:
#split train and testdata
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [122]:
#scale the features
Scaler=StandardScaler()
X_train=Scaler.fit_transform(X_train)
X_test=Scaler.transform(X_test)

In [123]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [124]:
with open("Scaler.pkl","wb")as file:
    pickle.dump(Scaler,file)

In [125]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

In [126]:
#bulid ann model
model=Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1,activation="sigmoid")
]
    
    
    )

c:\Users\supriya\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [127]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [128]:
#compile the parameters
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [129]:
#set up the tensorboard
tensorboard_callback=TensorBoard(log_dir="logs",histogram_freq=1)

In [130]:
#set up early stoppings
EarlyStopping=EarlyStopping(monitor="val_loss",patience=5)

In [131]:
#train the modelpochs=100, callbacks=[tensorboard_callback,EarlyStopping])
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100, callbacks=[tensorboard_callback,EarlyStopping])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8091 - loss: 0.4459 - val_accuracy: 0.8250 - val_loss: 0.3929
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8386 - loss: 0.3890 - val_accuracy: 0.8545 - val_loss: 0.3537
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8549 - loss: 0.3550 - val_accuracy: 0.8540 - val_loss: 0.3427
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8597 - loss: 0.3433 - val_accuracy: 0.8565 - val_loss: 0.3440
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8604 - loss: 0.3369 - val_accuracy: 0.8575 - val_loss: 0.3402
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8631 - loss: 0.3335 - val_accuracy: 0.8625 - val_loss: 0.3378
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8618 - loss: 0.3306 - val_accuracy: 0.8600 - val_loss: 0.3399
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8644 - loss: 0.3275 - val_accu

In [132]:
model.save("model.h5")

In [133]:
from tensorflow.keras.models import load_model


In [134]:
import os
os.listdir()


['ann.ipynb',
 'LabelEncoder_gender.pkl',
 'logs',
 'ml project',
 'ML PROJECTs',
 'model.h5',
 'OneHotEncoder_geo.pkl',
 'predict.analysis',
 'Scaler.pkl',
 'Untitled-2.ipynb']

In [135]:
model = load_model("model.h5")


In [149]:
#load the tensorflension
%tensorboard --logdir logs

Reusing TensorBoard on port 6006 (pid 19184), started 0:24:24 ago. (Use '!kill 19184' to kill it.)

In [137]:
# Gender LabelEncoder
with open("LabelEncoder_gender.pkl", "rb") as file:
    label_encoder_geo=pickle.load(file)

# Geography OneHotEncoder
with open("OneHotEncoder_geo.pkl", "rb") as file:
    LabelEncoder_gender=pickle.load(file)

# Feature Scaler
with open("Scaler.pkl", "rb") as file:
    scaler = pickle.load(file)


In [138]:
input_data = {
    "CreditScore": 650,
    "Geography": "France",
    "Gender": "Male",
    "Age": 40,
    "Tenure": 3,
    "Balance": 60000,
    "NumOfProducts": 1,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 50000
}

input_df = pd.DataFrame([input_data])



In [139]:
geo_encoded = onehot_encoder_geo.transform(input_df[['Geography']]).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)




In [140]:
input_data=pd.DataFrame([input_data])

In [141]:
input_data

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          650    France   Male   40       3    60000              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [142]:
#encode categorical columns
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
label_encoder_gender=LabelEncoder()
input_data["Gender"]=label_encoder_gender.fit_transform(input_data["Gender"])

In [143]:
#concatination one hot encoder
input_df=pd.concat([input_data.drop("Geography",axis=1),df],axis=1)

In [144]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
input_scaled = scaler.fit_transform(input_df)


In [145]:
#load the tensorflow extension
%load_ext tensorboard
%tensorboard --logdir logs

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6006 (pid 19184), started 0:23:07 ago. (Use '!kill 19184' to kill it.)

In [146]:
#prediction
prediction=model.predict(input_scaled)
prediction

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([[0.05175437],
       [0.3107683 ],
       [0.3107683 ],
       ...,
       [0.3107683 ],
       [0.3107683 ],
       [0.3107683 ]], dtype=float32)

In [152]:
prediction_prob=prediction[0][0] 
prediction_prob

0.051754374

In [148]:
model.input_shape


(None, 12)

In [153]:
if prediction_prob>0.5:
    print("the coustomer will churn")
else:
    print("the coustomer not churn")

the coustomer not churn
